[package]
name = "curves_rs"
version = "0.1.0"
authors = ["KarlWithK <jocelinc60@outlook.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
opt-level = 0
debug = true

[profile.release]
debug = 1
incremental = true
lto = "off"

# [dependencies]

[dev-dependencies]
criterion = "0.3.5"
num = "0.3.1"

# [[bench]]
# name = "derp"
# harness = false
